// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyv50ZW_rbdFq00Dh0Wf-KH_mHlZYdzVM',
    appId: '1:1059245792814:web:4c525bec3b711fa18689bf',
    messagingSenderId: '1059245792814',
    projectId: 'studynotes-377615',
    authDomain: 'studynotes-377615.firebaseapp.com',
    storageBucket: 'studynotes-377615.appspot.com',
    measurementId: 'G-FVE813D6NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWMPRaSijx6oMXWmYMWH6Qk8fcVUify_c',
    appId: '1:1059245792814:android:e52fc1bc3ecb49e98689bf',
    messagingSenderId: '1059245792814',
    projectId: 'studynotes-377615',
    storageBucket: 'studynotes-377615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeb5cIwyxEnmC4cDb9L8XinuCoel2Cnbc',
    appId: '1:1059245792814:ios:dc91e19905bebfdc8689bf',
    messagingSenderId: '1059245792814',
    projectId: 'studynotes-377615',
    storageBucket: 'studynotes-377615.appspot.com',
    androidClientId: '1059245792814-uh1r9kjq8e8rgldd629hne99829g60kv.apps.googleusercontent.com',
    iosClientId: '1059245792814-vrsgpgnt4uvtgg8c4ksfjfbhlk3ls6ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.studynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeb5cIwyxEnmC4cDb9L8XinuCoel2Cnbc',
    appId: '1:1059245792814:ios:dc91e19905bebfdc8689bf',
    messagingSenderId: '1059245792814',
    projectId: 'studynotes-377615',
    storageBucket: 'studynotes-377615.appspot.com',
    androidClientId: '1059245792814-uh1r9kjq8e8rgldd629hne99829g60kv.apps.googleusercontent.com',
    iosClientId: '1059245792814-vrsgpgnt4uvtgg8c4ksfjfbhlk3ls6ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.studynotes',
  );
}
